servers:
- id: server-1753347563582-5638
  name: aruba01
  type: network_device
  port: '22'
  host: aruba01.mynk.home
  is_extra: true
  is_new: false
  ping_enabled: true
  url: http://aruba01.mynk.home/
  tags: []
  description: ''
  auth_method: password
  username: admin
  password: apNeko330
  ssh_options: ''
  is_deleted: false
- id: server-1753347563582-3013
  name: blog
  type: node
  port: 22
  host: blog.mynk.home
  is_extra: true
  is_new: true
  ping_enabled: true
  tags: []
- id: server-1753347563582-1376
  name: box
  type: node
  port: 22
  host: box.mynk.home
  is_extra: true
  is_new: true
  ping_enabled: true
  tags: []
- id: server-1753347563582-7348
  name: cache
  type: virtual_machine
  port: '22'
  host: cache.mynk.home
  is_extra: true
  is_new: false
  ping_enabled: true
  url: ''
  tags: []
  description: ''
  auth_method: ssh_key
  username: nekoy
  ssh_key_id: sshkey-1752048252175
  parent_id: server-1753347563582-5396
  is_deleted: false
- id: server-1753347563582-4140
  name: db
  type: node
  port: 22
  host: db.mynk.home
  is_extra: true
  is_new: true
  ping_enabled: true
  tags: []
- id: server-1753347563582-4273
  name: deploy
  type: node
  port: 22
  host: deploy.mynk.home
  is_extra: true
  is_new: true
  ping_enabled: true
  tags: []
- id: server-1753347563582-2792
  name: dhcp
  type: node
  port: 22
  host: dhcp.mynk.home
  is_extra: true
  is_new: true
  ping_enabled: true
  tags: []
- id: server-1753347563582-3790
  name: dns
  type: node
  port: 22
  host: dns.mynk.home
  is_extra: true
  is_new: true
  ping_enabled: true
  tags: []
- id: server-1753347563582-5396
  name: docker
  type: node
  port: 22
  host: docker.mynk.home
  is_extra: true
  is_new: true
  ping_enabled: true
  tags: []
- id: vm-docker-web
  name: web-server
  type: virtual_machine
  port: '8080'
  host: web.docker.mynk.home
  is_extra: true
  ping_enabled: true
  url: http://web.docker.mynk.home:8080
  tags:
  - web
  - docker
  description: "Docker\u30CE\u30FC\u30C9\u4E0A\u306EWeb\u30B5\u30FC\u30D0\u30FCVM"
  auth_method: ssh_key
  username: webuser
  ssh_key_id: sshkey-1752048252175
  parent_id: server-1753347563582-5396
  is_deleted: true
- id: vm-docker-db
  name: database-vm
  type: virtual_machine
  port: '3306'
  host: db.docker.mynk.home
  is_extra: true
  ping_enabled: true
  url: ''
  tags:
  - database
  - mysql
  description: "Docker\u30CE\u30FC\u30C9\u4E0A\u306E\u30C7\u30FC\u30BF\u30D9\u30FC\
    \u30B9VM"
  auth_method: password
  username: dbadmin
  password: password123
  parent_id: server-1753347563582-5396
  is_deleted: true
- id: server-1753347563582-5711
  name: gcv
  type: node
  port: 22
  host: gcv.mynk.home
  is_extra: true
  is_new: true
  ping_enabled: true
  tags: []
- id: server-1753347563582-2363
  name: go-flow
  type: node
  port: 22
  host: go-flow.mynk.home
  is_extra: true
  is_new: true
  ping_enabled: true
  tags: []
- id: server-1753347563583-8303
  name: gw
  type: node
  port: 22
  host: gw.mynk.home
  is_extra: true
  is_new: true
  ping_enabled: true
  tags: []
- id: server-1753347563583-2450
  name: haos
  type: node
  port: 22
  host: haos.mynk.home
  is_extra: true
  is_new: true
  ping_enabled: true
  tags: []
- id: server-1753347563583-8767
  name: imm
  type: node
  port: 22
  host: imm.mynk.home
  is_extra: true
  is_new: true
  ping_enabled: true
  tags: []
- id: server-1753347563583-4542
  name: ipmi
  type: node
  port: 22
  host: ipmi.mynk.home
  is_extra: true
  is_new: true
  ping_enabled: true
  tags: []
- id: server-1753347563583-3226
  name: kibana
  type: node
  port: 22
  host: kibana.mynk.home
  is_extra: true
  is_new: true
  ping_enabled: true
  tags: []
- id: server-1753347563583-1023
  name: kuma
  type: node
  port: 22
  host: kuma.mynk.home
  is_extra: true
  is_new: true
  ping_enabled: true
  tags: []
- id: server-1753347563583-5143
  name: l2sw-1
  type: node
  port: 22
  host: l2sw-1.mynk.home
  is_extra: true
  is_new: true
  ping_enabled: true
  tags: []
- id: server-1753347563583-3232
  name: nas
  type: node
  port: 22
  host: nas.mynk.home
  is_extra: true
  is_new: true
  ping_enabled: true
  tags: []
- id: server-1753347563583-6950
  name: nas-share
  type: node
  port: 22
  host: nas-share.mynk.home
  is_extra: true
  is_new: true
  ping_enabled: true
  tags: []
- id: server-1753347563583-6674
  name: ns
  type: node
  port: 22
  host: ns.mynk.home
  is_extra: true
  is_new: true
  ping_enabled: true
  tags: []
- id: server-1753347563583-6192
  name: obsrv
  type: node
  port: 22
  host: obsrv.mynk.home
  is_extra: true
  is_new: true
  ping_enabled: true
  tags: []
- id: server-1753347563583-5259
  name: proxy
  type: node
  port: 22
  host: proxy.mynk.home
  is_extra: true
  is_new: true
  ping_enabled: true
  tags: []
- id: server-1753347563583-3287
  name: pve01
  type: node
  port: 22
  host: pve01.mynk.home
  is_extra: true
  is_new: true
  ping_enabled: true
  tags: []
- id: server-1753347563583-9677
  name: pve03
  type: node
  port: 22
  host: pve03.mynk.home
  is_extra: true
  is_new: true
  ping_enabled: true
  tags: []
- id: server-1753347563583-2862
  name: pve04
  type: node
  port: 22
  host: pve04.mynk.home
  is_extra: true
  is_new: true
  ping_enabled: true
  tags: []
- id: server-1753347563583-3526
  name: radius
  type: node
  port: 22
  host: radius.mynk.home
  is_extra: true
  is_new: true
  ping_enabled: true
  tags: []
- id: server-1753347563583-5443
  name: raspi
  type: node
  port: 22
  host: raspi.mynk.home
  is_extra: true
  is_new: true
  ping_enabled: true
  tags: []
- id: server-1753347563583-7650
  name: raspi2
  type: node
  port: 22
  host: raspi2.mynk.home
  is_extra: true
  is_new: true
  ping_enabled: true
  tags: []
- id: server-1753347563583-5754
  name: srv
  type: node
  port: 22
  host: srv.mynk.home
  is_extra: true
  is_new: true
  ping_enabled: true
  tags: []
- id: server-1753347563583-2310
  name: tsvpn
  type: node
  port: 22
  host: tsvpn.mynk.home
  is_extra: true
  is_new: true
  ping_enabled: true
  tags: []
- id: server-1753347563583-8025
  name: ups
  type: node
  port: 22
  host: ups.mynk.home
  is_extra: true
  is_new: true
  ping_enabled: true
  tags: []
- id: server-1753347563583-6491
  name: www
  type: node
  port: 22
  host: www.mynk.home
  is_extra: true
  is_new: true
  ping_enabled: true
  tags: []
