servers:
- id: server-1751995193436
  name: pve01
  type: node
  port: 22
  auth_method: key
  host: pve01.mynk.home
  username: root
  ssh_key_id: sshkey-1752048252175
  description: 'wa

    a

    a

    a'
- id: server-1751995236618
  name: "\u3063k"
  type: network_device
  port: 22
  auth_method: password
- id: server-1752076169048
  name: pve01
  type: virtual_machine
  port: 22
  auth_method: password
- id: server-1752076183092
  name: pve01
  type: virtual_machine
  port: 22
  auth_method: password
- id: server-1752076402122
  name: ldsmvoe
  type: network_device
  port: 22
  auth_method: password
- id: server-1752076413946
  name: ioefw
  type: kvm
  port: 22
  auth_method: password
  host: xx
  username: xx
  password: xx
  description: xxxx
- id: server-1752076428405
  name: dfbdfb
  type: virtual_machine
  port: 22
  auth_method: password
- id: server-1752116643170
  name: container
  type: kvm
  port: 22
  auth_method: password
