servers:
- id: server-1751995193436
  name: pve01
  type: node
  port: '22'
  auth_method: password
  host: pve01.mynk.home
  username: root
  ssh_key_id: sshkey-1752048252175
  description: 'wa

    a

    a'
  is_extra: false
  url: ''
  password: ''
  tags: ''
- id: server-1752076413946
  name: ioefw
  type: kvm
  port: 22
  auth_method: password
  host: xx
  username: xx
  password: xx
  description: xxxx
  is_extra: false
- id: server-1752151823363-7869
  name: dns
  type: node
  port: 22
  host: dns.mynk.home. 192.168.0.53
  is_extra: false
- id: server-1752166787906-7539
  name: srv
  type: node
  port: 22
  host: srv.mynk.home
  is_extra: true
- id: server-1752171950987-9997
  name: db
  type: node
  port: 22
  host: db.mynk.home
  is_extra: true
- id: server-1752171950987-6730
  name: dns
  type: node
  port: 22
  host: dns.mynk.home
  is_extra: true
- id: server-1752171950988-8278
  name: gw
  type: node
  port: 22
  host: gw.mynk.home
  is_extra: true
- id: server-1752171950988-6911
  name: haos
  type: node
  port: 22
  host: haos.mynk.home
  is_extra: true
- id: server-1752171950988-5038
  name: imm
  type: node
  port: 22
  host: imm.mynk.home
  is_extra: true
- id: server-1752171950988-2608
  name: ipmi
  type: node
  port: 22
  host: ipmi.mynk.home
  is_extra: true
- id: server-1752171950988-4944
  name: kibana
  type: node
  port: 22
  host: kibana.mynk.home
  is_extra: true
- id: server-1752171950988-4798
  name: kuma
  type: node
  port: 22
  host: kuma.mynk.home
  is_extra: true
- id: server-1752171950988-1833
  name: l2sw-1
  type: node
  port: 22
  host: l2sw-1.mynk.home
  is_extra: true
- id: server-1752171950988-7649
  name: nas
  type: node
  port: 22
  host: nas.mynk.home
  is_extra: true
- id: server-1752171950988-3971
  name: nas-share
  type: node
  port: 22
  host: nas-share.mynk.home
  is_extra: true
- id: server-1752171950988-6008
  name: ns
  type: node
  port: 22
  host: ns.mynk.home
  is_extra: true
- id: server-1752171950988-1377
  name: obsrv
  type: node
  port: 22
  host: obsrv.mynk.home
  is_extra: true
- id: server-1752171950988-7692
  name: proxy
  type: node
  port: 22
  host: proxy.mynk.home
  is_extra: true
- id: server-1752172236609-6477
  name: aruba01
  type: node
  port: 22
  host: aruba01.mynk.home
  is_extra: true
- id: server-1752172236609-9807
  name: blog
  type: node
  port: 22
  host: blog.mynk.home
  is_extra: true
- id: server-1752172236609-3274
  name: box
  type: node
  port: 22
  host: box.mynk.home
  is_extra: true
- id: server-1752172697489-1617
  name: deploy
  type: node
  port: 22
  host: deploy.mynk.home
  is_extra: true
- id: server-1752172697489-6248
  name: dhcp
  type: node
  port: 22
  host: dhcp.mynk.home
  is_extra: true
- id: server-1752172997567-9536
  name: docker
  type: node
  port: 22
  host: docker.mynk.home
  is_extra: true
- id: server-1752175640662-1558
  name: pve04
  type: node
  port: 22
  host: pve04.mynk.home
  is_extra: true
- id: server-1752175640662-5275
  name: radius
  type: node
  port: 22
  host: radius.mynk.home
  is_extra: true
- id: server-1752214320787-3456
  name: gcv
  type: node
  port: 22
  host: gcv.mynk.home
  is_extra: true
- id: server-1752214320788-7554
  name: go-flow
  type: node
  port: 22
  host: go-flow.mynk.home
  is_extra: true
- id: server-1752214320788-3029
  name: pve03
  type: node
  port: 22
  host: pve03.mynk.home
  is_extra: true
- id: server-1752218996427-6854
  name: cache
  type: node
  port: 22
  host: cache.mynk.home
  is_extra: true
- id: server-1752218996427-9732
  name: raspi
  type: node
  port: 22
  host: raspi.mynk.home
  is_extra: true
- id: server-1752218996427-3119
  name: raspi2
  type: node
  port: 22
  host: raspi2.mynk.home
  is_extra: true
- id: server-1752218996427-3972
  name: tsvpn
  type: node
  port: 22
  host: tsvpn.mynk.home
  is_extra: true
- id: server-1752218996427-8059
  name: ups
  type: node
  port: 22
  host: ups.mynk.home
  is_extra: true
- id: server-1752218996427-6148
  name: www
  type: node
  port: 22
  host: www.mynk.home
  is_extra: true
