servers:
- id: server-1752480452059-6569
  name: cache
  type: node
  port: 22
  host: cache.mynk.home
  is_extra: true
- id: server-1752480452059-3956
  name: db
  type: node
  port: 22
  host: db.mynk.home
  is_extra: true
- id: server-1752480452059-2417
  name: deploy
  type: node
  port: 22
  host: deploy.mynk.home
  is_extra: true
- id: server-1752480452059-1616
  name: dhcp
  type: node
  port: 22
  host: dhcp.mynk.home
  is_extra: true
- id: server-1752480452059-5291
  name: dns
  type: node
  port: 22
  host: dns.mynk.home
  is_extra: true
- id: server-1752480452059-2251
  name: docker
  type: node
  port: 22
  host: docker.mynk.home
  is_extra: true
- id: server-1752480452059-7710
  name: gcv
  type: node
  port: 22
  host: gcv.mynk.home
  is_extra: true
- id: server-1752480452059-5551
  name: go-flow
  type: node
  port: 22
  host: go-flow.mynk.home
  is_extra: true
- id: server-1752480452060-3498
  name: gw
  type: node
  port: 22
  host: gw.mynk.home
  is_extra: true
- id: server-1752480452060-4698
  name: haos
  type: node
  port: 22
  host: haos.mynk.home
  is_extra: true
- id: server-1752480452064-9394
  name: imm
  type: node
  port: 22
  host: imm.mynk.home
  is_extra: true
- id: server-1752480452064-3103
  name: ipmi
  type: node
  port: 22
  host: ipmi.mynk.home
  is_extra: true
- id: server-1752480452064-2919
  name: kibana
  type: node
  port: 22
  host: kibana.mynk.home
  is_extra: true
- id: server-1752480452064-3079
  name: kuma
  type: node
  port: 22
  host: kuma.mynk.home
  is_extra: true
- id: server-1752480452064-7249
  name: l2sw-1
  type: node
  port: 22
  host: l2sw-1.mynk.home
  is_extra: true
- id: server-1752480452064-8614
  name: nas
  type: node
  port: 22
  host: nas.mynk.home
  is_extra: true
- id: server-1752480452064-4997
  name: nas-share
  type: node
  port: 22
  host: nas-share.mynk.home
  is_extra: true
- id: server-1752480452064-6653
  name: ns
  type: node
  port: 22
  host: ns.mynk.home
  is_extra: true
- id: server-1752480452064-5860
  name: obsrv
  type: node
  port: 22
  host: obsrv.mynk.home
  is_extra: true
- id: server-1752480452064-9618
  name: proxy
  type: node
  port: 22
  host: proxy.mynk.home
  is_extra: true
- id: server-1752480452064-4448
  name: pve01
  type: node
  port: 22
  host: pve01.mynk.home
  is_extra: true
- id: server-1752480452064-2777
  name: pve03
  type: node
  port: 22
  host: pve03.mynk.home
  is_extra: true
- id: server-1752480452064-5398
  name: pve04
  type: node
  port: 22
  host: pve04.mynk.home
  is_extra: true
- id: server-1752480452064-6146
  name: radius
  type: node
  port: 22
  host: radius.mynk.home
  is_extra: true
- id: server-1752480452064-6206
  name: raspi
  type: node
  port: 22
  host: raspi.mynk.home
  is_extra: true
- id: server-1752480452064-7595
  name: raspi2
  type: node
  port: 22
  host: raspi2.mynk.home
  is_extra: true
- id: server-1752480452064-2482
  name: srv
  type: node
  port: 22
  host: srv.mynk.home
  is_extra: true
- id: server-1752480452064-2802
  name: tsvpn
  type: node
  port: 22
  host: tsvpn.mynk.home
  is_extra: true
- id: server-1752480452064-4719
  name: ups
  type: node
  port: 22
  host: ups.mynk.home
  is_extra: true
- id: server-1752480452064-2394
  name: www
  type: node
  port: 22
  host: www.mynk.home
  is_extra: true
